WebProProjekt/WebProProjekt/Models/OurPicUploads.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebProProjekt.Models
{
	public class OurPicUploads
	{
		[Key]
		public int Id { get; set; }

		[Required]
		[DisplayName("The heckin' title of yo pic (May not contain < > . or new line)")]
		//[RegularExpression("([^(<>\n.)])*")]
		public string? PicTitle { get; set; }

		[Required]
		[DisplayName("Describe your pic !!!(May not contain < > . or new line)")]
		[RegularExpression("([^(<>\n.)])*")]
		public string? PicDescription { get; set; }
		
		public string? PicPath { get; set; }

		public required string ProfileId { get; set; }

		[Required]
		[DisplayName("Pic u have to upload")]
		[NotMapped]
        public IFormFile PicFile { get; set; }

		
	}
}

WebProProjekt/WebProProjekt/Controllers/OurPicUploadsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using WebProProjekt.Data;
using WebProProjekt.Data.Migrations;
using WebProProjekt.Models;
using WebProProjekt.ViewModel;


namespace WebProProjekt.Controllers
{
    [Authorize]
    public class OurPicUploadsController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IWebHostEnvironment _hostEnvironment;

        public OurPicUploadsController(ApplicationDbContext context, UserManager<IdentityUser> userManager, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _hostEnvironment = hostEnvironment;
        }

		public async Task<IActionResult> Index()
		{
			return View(await _context.OurPicUpload.ToListAsync());
		}
		public IActionResult ShowOurPicUploads() //Displays the picture when called
        {
            Display display = new Display(); //Makes new object for the picture
            display.pics = _context.OurPicUpload.ToList(); //Goes into the viewmodel Display and gets the pics list from the database and puts them into the list to display
            display.IUser = _context.Users.ToList(); //The same as before, but here its the data about the user who put up the picture

            return View(display); //Returns a view with the pictures
        }

		// GET: OurPicUploads/Details/5
		public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ourPicUpload = await _context.OurPicUpload
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ourPicUpload == null)
            {
                return NotFound();
            }

            return View(ourPicUpload);
        }

        // GET: OurPicUploads/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: OurPicUploads/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OurPicUploads ourPicUpload)
        {

            var user = await _userManager.GetUserAsync(User);
            if (user == null) return Unauthorized();

            ourPicUpload.ProfileId = user.Id;

			ModelState.Remove("ProfileId");
			if (ourPicUpload.PicFile != null && ModelState.IsValid) //ModelState.IsValid tjekker om kravende til modellen er opfyldt
			{
                var allowedExtensions = new[] { ".jpg", ".png", ".jpeg" }; 
                var checkExtension = Path.GetExtension(ourPicUpload.PicFile.FileName).ToLower();
                var picName = Path.GetFileNameWithoutExtension(ourPicUpload.PicFile.FileName);
                var extension = Path.GetExtension(ourPicUpload.PicFile.FileName);
                picName = picName + DateTime.Now.ToString("yymmssfff") + extension;

                //cross site scripting
                StringBuilder titleSB = new StringBuilder();
                titleSB.Append(HttpUtility.HtmlEncode(ourPicUpload.PicTitle));
                StringBuilder desSB = new StringBuilder();
                desSB.Append(HttpUtility.HtmlEncode(ourPicUpload.PicDescription));

                titleSB.Replace("&#230;", "æ");
                titleSB.Replace("&#248;", "ø");
                titleSB.Replace("&#229;", "å");

                desSB.Replace("&#230;", "æ");
                desSB.Replace("&#248;", "ø"); //Den burde vise ø men det gør den ikke?
                desSB.Replace("&#229;", "å");

                ourPicUpload.PicTitle = titleSB.ToString();
                ourPicUpload.PicDescription = desSB.ToString();


                var uploadPath = Path.Combine(_hostEnvironment.WebRootPath, "Pics");
				if (!Directory.Exists(uploadPath))
				{
					Directory.CreateDirectory(uploadPath);
				}

				var path = Path.Combine(_hostEnvironment.WebRootPath + "/Pics/", picName);

                if (!allowedExtensions.Contains(checkExtension))
                {
                    ModelState.AddModelError("PicFile", "Invalid file format.");
                    return RedirectToAction("OurPicUpload");
                }

                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await ourPicUpload.PicFile.CopyToAsync(fileStream);
                }

                ourPicUpload.PicPath = picName;

				ModelState.AddModelError("PicFile", "Please upload a file");


				_context.Add(ourPicUpload);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(ShowOurPicUploads));
                
			}

            

            return View(ourPicUpload);

        }

        // GET: OurPicUploads/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ourPicUpload = await _context.OurPicUpload.FindAsync(id);
            if (ourPicUpload == null)
            {
                return NotFound();
            }
            return View(ourPicUpload);
        }

        // POST: OurPicUploads/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,OurPicUploads ourPicUpload)
        {
            //cross site scripting
            StringBuilder titleSB = new StringBuilder();
            titleSB.Append(HttpUtility.HtmlEncode(ourPicUpload.PicTitle));
            StringBuilder desSB = new StringBuilder();
            desSB.Append(HttpUtility.HtmlEncode(ourPicUpload.PicDescription));

            titleSB.Replace("&#230;", "æ");
            titleSB.Replace("&#248;", "ø");
            titleSB.Replace("&#229;", "å");

            desSB.Replace("&#230;", "æ");
            desSB.Replace("&#248;", "ø"); //Den burde vise ø men det gør den ikke?
            desSB.Replace("&#229;", "å");

            ourPicUpload.PicTitle = titleSB.ToString();
            ourPicUpload.PicDescription = desSB.ToString();
            if (id != ourPicUpload.Id)
            {
                return NotFound();
            }

            ModelState.Remove("ProfileId");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ourPicUpload);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OurPicUploadExists(ourPicUpload.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ourPicUpload);
        }

        // GET: OurPicUploads/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ourPicUpload = await _context.OurPicUpload
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ourPicUpload == null)
            {
                return NotFound();
            }

            return View(ourPicUpload);
        }

        // POST: OurPicUploads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ourPicUpload = await _context.OurPicUpload.FindAsync(id);
            if (ourPicUpload != null)
            {
                _context.OurPicUpload.Remove(ourPicUpload);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OurPicUploadExists(int id)
        {
            return _context.OurPicUpload.Any(e => e.Id == id);
        }
    }
}

WebProProjekt/WebProProjekt/Views/OurPicUploads/Create.cshtml
@model WebProProjekt.Models.OurPicUploads

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>



<h4>OurPicUpload</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="OurPicUploads" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PicTitle" class="control-label"></label>
                <input asp-for="PicTitle" class="form-control" />
                <span asp-validation-for="PicTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PicDescription" class="control-label"></label>
                <input asp-for="PicDescription" class="form-control"/>
                <span asp-validation-for="PicDescription" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="PicFile" class="control-label"></label>
                <input asp-for="PicFile" type="file" class="form-control" />
                <span asp-validation-for="PicFile" class="text-danger"></span>
            </div>
            <div class="form-group" id="createButton">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <script>
                function Validator() {
                    let picTit = document.getElementById("PicTitle").value;
                    let picDic = document.getElementById("PicDescription").value;
                    let picFile = document.getElementById("PicFile").value;
                    console.log("Outer");
                    while (picTit || picDic || picFile) {
                        console.log("Hello");
                        document.getElementsById("createButton").disabled = true;
                    }
                }
            </script>
        </form>
    </div>
</div>



<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebProProjekt/WebProProjekt/Views/OurPicUploads/Delete.cshtml
@model WebProProjekt.Models.OurPicUploads

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OurPicUpload</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PicTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PicTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PicDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PicDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PicPath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PicPath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfileId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfileId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebProProjekt/WebProProjekt/Views/OurPicUploads/Details.cshtml
@model WebProProjekt.Models.OurPicUploads

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>OurPicUpload</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PicTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PicTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PicDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PicDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PicPath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PicPath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfileId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfileId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebProProjekt/WebProProjekt/Views/OurPicUploads/Edit.cshtml
@model WebProProjekt.Models.OurPicUploads

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>OurPicUpload</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PicTitle" class="control-label"></label>
                <input asp-for="PicTitle" class="form-control" />
                <span asp-validation-for="PicTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PicDescription" class="control-label"></label>
                <input asp-for="PicDescription" class="form-control" />
                <span asp-validation-for="PicDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PicPath" class="control-label"></label>
                <input asp-for="PicPath" class="form-control" />
                <span asp-validation-for="PicPath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfileId" class="control-label"></label>
                <input asp-for="ProfileId" class="form-control" />
                <span asp-validation-for="ProfileId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebProProjekt/WebProProjekt/Views/OurPicUploads/Index.cshtml
@model IEnumerable<WebProProjekt.Models.OurPicUploads>

@{
	ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
	<a asp-action="Create">Create New</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.PicTitle)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.PicDescription)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.PicPath)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.ProfileId)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.PicTitle)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.PicDescription)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.PicPath)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.ProfileId)
				</td>
				<td>
					<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
					<a asp-action="Details" asp-route-id="@item.Id">Details</a> |
					<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
				</td>
			</tr>
		}
	</tbody>
</table>

WebProProjekt/WebProProjekt/Views/OurPicUploads/ShowOurPicUploads.cshtml
@using WebProProjekt.ViewModel
@model Display


<h1>users in database!</h1>
@foreach (var user in Model.IUser) //All users in database
{
	
	<div>
		this is a user: @user.UserName
	</div>
}
@foreach (var user in Model.IUser) //All users in database
{
	@foreach (var post in Model.pics) //all the pictures in the database
	{
		@if (user.Id == post.ProfileId)
		{
			<h1>
				Show dem pics hokus pokus!
			</h1>
			<div>
				this person @user.UserName 's picture'
				<br>
				Pic is called @post.PicTitle
				<p id="picDis">
					@post.PicDescription
				</p>
				<img src="~/Pics/@post.PicPath" alt="LOL CANT SHOW DIS" />

							<form asp-action="Delete">
					<input type="hidden" asp-for="id" />
					<input type="submit" value="Delete" class="btn btn-danger" /> |
					<a asp-action="Index">Back to List</a>
				</form>
			</div>
		}
	}
}